QManager/QManager/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QManager.Models
{
    public class Usuario
    {
        public int ID { get; set; }

        public string Nome { get; set; }

        public string QuantidadePessoas { get; set; }

        public string DataHoraChegada { get; set; }
    }
}

QManager/QManager/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

QManager/QManager/Controllers/EstatisticaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class EstatisticaController : Controller
    {
        // GET: Estatistica
        public ActionResult Index()
        {
            return View();
        }
    }
}

QManager/QManager/Controllers/FilaController.cs
using Newtonsoft.Json;
using QManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class FilaController : Controller
    {
        // GET: Fila
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Remover(int id)
        {
            List<Usuario> listaUsuario = new List<Usuario>();

            using (StreamReader sr = new StreamReader(Server.MapPath("~/Mock/Usuario.json"), true))
            {
                listaUsuario = JsonConvert.DeserializeObject<List<Usuario>>(sr.ReadToEnd());

                sr.Close();
            }

            var usuario = listaUsuario.Where(m => m.ID == id).FirstOrDefault();
            listaUsuario.Remove(usuario);

            for (int i = 0; i < listaUsuario.Count; i++)
            {
                listaUsuario[i].ID = i + 1;
            }

            string json = JsonConvert.SerializeObject(listaUsuario.ToArray());

            using (StreamWriter sw = new StreamWriter(Server.MapPath("~/Mock/Usuario.json")))
            {
                sw.Write(json);

                sw.Close();
            }

            ViewBag.Mensagem = "Usuário removido com sucesso!";

            return View("Index");
        }
    }
}

QManager/QManager/Controllers/HomeController.cs
using Newtonsoft.Json;
using QManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Usuario> listaUsuario = new List<Usuario>();

            using (StreamReader sr = new StreamReader(Server.MapPath("~/Mock/Usuario.json"), true))
            {
                listaUsuario = JsonConvert.DeserializeObject<List<Usuario>>(sr.ReadToEnd());

                sr.Close();
            }

            ViewBag.TotalFila = string.Format("{0} pessoa(s)", listaUsuario.Count());

            return View();
        }
    }
}

QManager/QManager/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Acessar()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

QManager/QManager/Controllers/UsuarioController.cs
using Newtonsoft.Json;
using QManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QManager.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        public ActionResult Index()
        {
            var dateTime = DateTime.Now;

            Usuario usuario = new Usuario()
            {
                DataHoraChegada = string.Format("{0}/{1}/{2} {3}:{4}", dateTime.Day,
                                                                       dateTime.Month,
                                                                       dateTime.Year,
                                                                       dateTime.Hour,
                                                                       dateTime.Minute)
            };

            if (TempData["Mensagem"] != null)
            {
                ViewBag.Mensagem = TempData["Mensagem"];
            }

            return View(usuario);
        }

        public ActionResult Adicionar(Usuario usuario)
        {
            try
            {
                List<Usuario> listaUsuario = new List<Usuario>();

                using (StreamReader sr = new StreamReader(Server.MapPath("~/Mock/Usuario.json"), true))
                {
                    listaUsuario = JsonConvert.DeserializeObject<List<Usuario>>(sr.ReadToEnd());
                }

                if (listaUsuario.Count == 10)
                {
                    ViewBag.Mensagem = "Limite máximo de usuários na fila excedido (10 usuários)";


                    var dataHora = DateTime.Now;
                    usuario.DataHoraChegada = string.Format("{0}/{1}/{2} {3}:{4}", dataHora.Day,
                                                                           dataHora.Month,
                                                                           dataHora.Year,
                                                                           dataHora.Hour,
                                                                           dataHora.Minute);

                    return View("Index", usuario);
                }
                else
                {
                    listaUsuario.Add(new Usuario()
                    {
                        Nome = usuario.Nome,
                        QuantidadePessoas = usuario.QuantidadePessoas,
                        DataHoraChegada = usuario.DataHoraChegada,
                        ID = listaUsuario.Count + 1
                    });

                    string json = JsonConvert.SerializeObject(listaUsuario.ToArray());

                    using (StreamWriter sw = new StreamWriter(Server.MapPath("~/Mock/Usuario.json")))
                    {
                        sw.Write(json);
                    }
                }

                TempData["Mensagem"] = "Usuário adicionado com sucesso!";

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.Mensagem = "Ocorreu um erro. Favor tente novamente!";

                var dateTime = DateTime.Now;
                usuario = new Usuario()
                {
                    DataHoraChegada = string.Format("{0}/{1}/{2} {3}:{4}", dateTime.Day,
                                                                       dateTime.Month,
                                                                       dateTime.Year,
                                                                       dateTime.Hour,
                                                                       dateTime.Minute)
                };

                return View("Index", usuario);
            }
        }
    }
}

QManager/QManager/Views/About/Index.cshtml
@{
    ViewBag.Title = "> Sobre Nós";
}

<div id="about_content" class="page-content">
    <div class="mdl-grid">
        <section class="mdl-cell mdl-cell--12-col mdl-shadow--2dp">
            <div class="mdl-card mdl-cell mdl-cell--12-col">
                <div class="mdl-card__supporting-text">
                    <h4>Engenharia Web - SENAC</h4>
                    <h5>Gerenciamento de fila de espera por meio de dispositivo móvel</h5>
                    <p>Integrantes:</p>
                    <p>Cristiano Conter</p>
                    <p>Diogo Akira Wakabayashi</p>
                    
                    <h5>Tecnologias utilizadas</h5>
                    <ul>
                        <li>Asp.Net MVC</li>
                        <li>C#</li>
                        <li>Google Fonts (https://fonts.googleapis.com/)</li> 
                        <li>Material Design (https://code.getmdl.io/)</li>
                        <li>jQuery (https://code.jquery.com)</li>
                        <li>HTML 5</li>
                        <li>CSS 3</li>
                        <li>Responsividade</li>
                    </ul>
                    <p>
                        <a href="https://github.com/diakira/qmanager">
                            <img src="~/Layout/github.svg" alt="github" style="width:28px"/>
                            https://github.com/diakira/qmanager
                        </a>
                    </p>
                </div>
            </div>

        </section>
    </div>
</div>

QManager/QManager/Views/Fila/Index.cshtml
@{
    ViewBag.Title = "> Fila";
}

<script type="text/javascript">
    $(function () {
        $.getJSON("@Url.Content("~/Mock/Usuario.json")", function (data) {
            $("#tabela").html("");
            for (var i = 0; i < data.length; i++) {

                $("#tabela").append(
                              '<li class="mdl-list__item mdl-list__item--three-line">'
                               + '<span class="mdl-list__item--number">'
                               + '<a href="@Url.Action("Remover","Fila")?id=' + data[i].ID + '">'
                               + '<div id="tt' + i + '" class="icon material-icons fila_delete">delete_forever</div>'
                               + '<div class="mdl-tooltip" for="tt' + i + '">'
                               + '  Remover da fila'
                               + '</div>'
                               + '</a>'
                              + '</span>'
                                   + '<span class="mdl-list__item--number">'
                                 + (i + 1) + 'º'
                              + '</span>'
                              + '   <span class="mdl-list__item-primary-content">'
                              + '       <i class="material-icons mdl-list__item-avatar">person</i>'
                              + '   <span>'
                               + data[i].Nome
                              + '</span>'
                              + '<span class="mdl-list__item-text-body">'
                              + 'Chegou em '
                              + data[i].DataHoraChegada
                                + ' com '
                              + data[i].QuantidadePessoas
                              + ' pessoas'
                              + '</span>'
                              + '</span>'
                              + '<span class="mdl-list__item-secondary-content">'
                              + '    <span class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" onclick="Chamar(\'' + data[i].Nome + '\')">'
                              + '    chamar'
                              + '    </span>'
                              + '</span>'
                              + '</li>'
                );
            };
        });

        var dialog = document.querySelector('dialog');

        dialog.querySelector('.close').addEventListener('click', function () {
            dialog.close();
            $(".mdl-dialog").hide();
        });

        var mensagem = "@ViewBag.Mensagem"

        if (mensagem != "") {
            dialog.showModal();
            $(".mdl-dialog").show();
        }
    });

    function Chamar(nome) {

        $("#mensagemDialog").text("Você chamou " + nome);
        var dialog = document.querySelector('dialog#dialogChamar');
        var showDialogButton = document.querySelector('#show-dialog');
       
        dialog.querySelector('.close').addEventListener('click', function () {
            dialog.close();
            $(".mdl-dialog").hide();
        });

        dialog.showModal();
        $("#dialogChamar").show();
    };
</script>

<div id="fila_content" class="page-content mdl-grid">

    <section class="mdl-cell mdl-cell--12-col mdl-shadow--2dp">

        <div class="mdl-cell mdl-cell--7-col">
            <ul id="tabela" class="demo-list-two mdl-list"></ul>
        </div>
    </section>


    <dialog class="mdl-dialog" style="display:none">
        <div class="mdl-dialog__content">
            <p>
                @ViewBag.Mensagem
            </p>
        </div>
        <div class="mdl-dialog__actions">
            <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent close">
                <i class="material-icons">done</i> OK
            </button>
        </div>
    </dialog>
</div>

<dialog id="dialogChamar" class="mdl-dialog" style="display:none">
    <div class="mdl-dialog__content">
        <p>
            <span id="mensagemDialog">
            </span>
        </p>
    </div>
    <div class="mdl-dialog__actions">
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent close">
            <i class="material-icons">done</i> OK
        </button>
    </div>
</dialog>

QManager/QManager/Views/Home/Index - Copy.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="container">


    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />

    <ul id="discussion"></ul>

    <select id="listaUser" size="5"></select>


</div>

@section Scripts
{
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script type="text/javascript">
        $(function () {
            //Set the hubs URL for the connection
            //  $.connection.hub.url = "http://localhost/appSignalR/signalr";
            // Reference the auto-generated proxy for the hub.

            var chat = $.connection.qManagerHub;

            // Start the connection.
            $.connection.hub.start().done(function () {
                chat.server.enviarIdManager($.connection.hub.id);

                $("#sendmessage").click(function () {
                    chat.server.enviarMensagem($('#listaUser option:selected').val(), $("#message").val());
                });
            });

            chat.client.AdicionarMensagem = function (mensagem) {
                //$("#messageUser").val(mensagem);
                $('#discussion').append('<li>' + htmlEncode(mensagem) + '</li>');
            }

            // Create a function that the hub can call back to display messages.
            chat.client.ReceberPosicao = function (posicao) {
                // Add the message to the page.
                $('#message').val(posicao);
            };

            chat.client.AdicionarLista = function (id, name) {
                $('#listaUser').append($('<option>', {
                    value: id,
                    text: name
                }));
            }

            chat.client.RemoverLista = function (id) {
                $('#listaUser option[value=' + id + ']').remove();
            }
        });

        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

QManager/QManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "";
}

<div id="home_content" class="page-content">   
    <div id="tiles" class="mdl-grid">
        <a href="@Url.Action("Index","Fila")" id="tile_fila" class="mdl-cell mdl-cell--4-col mdl-cell--8-col-tablet demo-cell mdl-shadow--6dp tile mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons mdl-cell mdl-cell--12-col">list</i>
            <label class="tile_title mdl-cell--12-col">Fila</label>
            <div>
                <label class="mdl-cell--12-col">@ViewBag.TotalFila</label>
            </div>
        </a>

        <a href="@Url.Action("Index","Usuario")" id="tile_usuario" class="mdl-cell mdl-cell--4-col demo-cell mdl-shadow--6dp tile mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons mdl-cell--12-col">account_box</i>
            <label class="tile_title">Usuários</label>
        </a>

        <a href="@Url.Action("Index","Estatistica")" id="tile_estatistica" class="mdl-cell mdl-cell--4-col demo-cell mdl-shadow--6dp tile mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons md-48 mdl-cell--12-col">show_chart</i>
            <label class="tile_title">Estatísticas</label>
        </a>

        <a href="@Url.Action("Index","About")" id="tile_about" class="mdl-cell mdl-cell--4-col demo-cell mdl-shadow--6dp tile mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
            <i class="material-icons md-48 mdl-cell--12-col">people</i>            
            <label class="tile_title">Sobre Nós</label>
        </a>
    </div>
</div>

QManager/QManager/Views/Login/Index.cshtml
@{
    ViewBag.Title = "QManager";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>QManager</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue_grey-blue.min.css" />
    <style>
        html, body {
            font-family: 'Roboto', 'Helvetica', sans-serif;
        }

        main {
            background-color: #F5F5F5;
        }

            main section {
                margin: 30px 10px 0px 10px !important;
                background-color: white;
            }


        #loader {
            position: fixed;
            z-index: 999;
            height: 2em;
            width: 2em;
            margin: auto;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }

            #loader:before {
                content: '';
                display: block;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0,0,0,0.3);
            }
    </style>
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $("a, .mdl-button").click(function () {
                $("#loader").show();
            });
        })

    </script>
</head>
<body>
    @using (Html.BeginForm("Acessar", "Login", FormMethod.Post))
    {
        <div style="display:none" id="loader">
            <img src="~/Layout/loading.svg" class="loading" style="width: 100px;" alt="loading" />
        </div>
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
            <header class="mdl-layout__header">
                <div class="mdl-layout__header-row">
                    <!-- Title -->
                    <span class="mdl-layout-title">QManager</span>
                    <!-- Add spacer, to align navigation to the right -->
                    <div class="mdl-layout-spacer"></div>
                    <!-- Navigation. We hide it in small screens. -->
                </div>
            </header>

            <main class="mdl-layout__content">
                <div class="page-content">
                    <div class="mdl-grid">
                        <div class="mdl-layout-spacer"></div>

                        <div class="mdl-cell mdl-cell--4-col mdl-typography--text-center mdl-shadow--6dp" style="background-color:white; padding:20px">
                            <div>
                                <img src="~/Layout/qManager-logo-BI.png" alt="qManager" />
                            </div>
                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="text-align:center">
                                <input class="mdl-textfield__input" type="text" id="nome">
                                <label class="mdl-textfield__label" for="nome">Usuário</label>
                            </div>

                            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                                <input class="mdl-textfield__input" type="password" id="nome">
                                <label class="mdl-textfield__label" for="nome">Senha</label>
                            </div>
                            <div class="mdl-layout-spacer"></div>
                            <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                                Entrar
                            </button>

                        </div>
                        <div class="mdl-layout-spacer"></div>
                    </div>
                </div>
            </main>
        </div>
    }
</body>
</html>

QManager/QManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="A front-end template that helps you build fast, modern mobile web apps.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>QManager</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.blue_grey-blue.min.css" />

    <style>
        html, body {
            font-family: 'Roboto', 'Helvetica', sans-serif;
        }

        .demo-cell {
            background-color: #BDBDBD;
            height: 200px;
            margin: 8px;
        }

        #sidebar a {
            text-align: left;
        }

        main {
            background-color: #F5F5F5;
        }

            main section {
                margin: 30px 10px 0px 10px !important;
                background-color: white;
            }

        .demo-charts {
            align-items: center;
        }

        .demo-chart:nth-child(1) {
            color: #ACEC00;
        }

        .demo-chart:nth-child(2) {
            color: #00BBD6;
        }

        .demo-chart:nth-child(3) {
            color: #BA65C9;
        }

        .demo-chart:nth-child(4) {
            color: #EF3C79;
        }

        .demo-graphs {
            padding: 16px 32px;
            display: flex;
            flex-direction: column;
            align-items: stretch;
        }

        .demo-graph:nth-child(1) {
            color: #00b9d8;
        }

        .demo-graph:nth-child(2) {
            color: #d9006e;
        }

        .mdl-list__item--number {
            font-size: 30px;
            margin-right: 15px;
        }

        .tile {
            cursor: pointer;
            text-align: center;
        }

            .tile .material-icons {
                font-size: 100px;
                color: white;
            }

        #tile_fila {
            background-color: #303F9F;
        }

        #tile_usuario {
            background-color: #8BC34A;
        }

        #tile_estatistica {
            background-color: #FF5722;
        }

        #tile_about {
            background-color: #FFC107;
        }

        .tile_title {
            font-size: x-large;
            color: white;
            position: relative;
            bottom: 0;
        }

        .mdl-layout-title a {
            color: #fff;
        }

        #tiles a {
            text-decoration: none;
        }

        #tile_home {
            text-decoration: none;
            font-weight: bold;
        }

        .fila_delete {
            color: #d50000;
        }

        #loader {
            position: fixed;
            z-index: 999;
            height: 2em;
            width: 2em;
            margin: auto;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
        }

            #loader:before {
                content: '';
                display: block;
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background-color: rgba(0,0,0,0.3);
            }

        dialog#dialogChamar.mdl-dialog {
            top: 0;
        }
    </style>
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script scr="http://ajax.aspnetcdn.com/ajax/mvc/4.0/jquery.validate.unobtrusive.min.js"></script>
</head>

<body style="height:100%">
    <div style="display:none" id="loader">
        <img src="~/Layout/loading.svg" class="loading" style="width: 100px;" alt="loading" />
    </div>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
        <header class="mdl-layout__header ">
            <div class="mdl-layout__header-row">
                <div class="mdl-layout-spacer mdl-layout-title">
                    <div style="float:left">
                        <a href="@Url.Action("Index","Home")" id="tile_home">HOME</a> <span id="page_title">@ViewBag.Title </span>
                    </div>
                    <div style="text-align:right">
                        <a href="@Url.Action("Index","Login")"><div id="ttsair" class="icon material-icons">exit_to_app</div></a>
                        <div class="mdl-tooltip" for="ttsair">
                            Sair
                        </div>
                    </div>

                </div>
            </div>
        </header>

        <div id="sidebar" class="mdl-layout__drawer">
            <span class="mdl-layout-title"><a href="@Url.Action("Index","Home")"><img src="~/Layout/qManager-logo-BI.png" alt="qManager" /></a></span>
            <nav class="mdl-navigation">
                <a id="home" class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect" href="@Url.Action("Index","Home")"><i class="material-icons">home</i> Home</a>
                <a id="fila" class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect" href="@Url.Action("Index","Fila")"><i class="material-icons">list</i> Fila</a>
                <a id="usuario" class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect" href="@Url.Action("Index","Usuario")"><i class="material-icons">account_box</i> Usuários</a>
                <a id="estatistica" class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect" href="@Url.Action("Index","Estatistica")"><i class="material-icons">show_chart</i> Estatísticas</a>
                <a id="about" class="mdl-navigation__link mdl-button mdl-js-button mdl-js-ripple-effect" href="@Url.Action("Index","About")"><i class="material-icons">people</i> Sobre Nós</a>
            </nav>
        </div>

        <main class="mdl-layout__content">
            @RenderBody()
        </main>
    </div>
    <script type="text/javascript">
        $(function () {
            @RenderSection("scripts", required: false)

            $("a, .mdl-button").click(function () {
                $("#loader").show();
            });

            $(".close").click(function () {
                $("#loader").hide();
            });
        })
    </script>
</body>
</html>

QManager/QManager/Views/Usuario/Index.cshtml
@model QManager.Models.Usuario

@{
    ViewBag.Title = "> Usuários";
}

<script>

    $(function () {

        var dialog = document.querySelector('dialog');
      
        dialog.querySelector('.close').addEventListener('click', function () {
            dialog.close();
            $(".mdl-dialog").hide();
        });

        var mensagem = '@ViewBag.Mensagem'

        if (mensagem != "") {
            dialog.showModal();
            $(".mdl-dialog").show();
        }
    })
</script>

<div id="usuario_content" class="page-content">
    @using (Html.BeginForm("Adicionar", "Usuario"))
    {

        <div class="mdl-grid">
            <section class="mdl-cell mdl-cell--12-col mdl-shadow--2dp  mdl-typography--text-center">

                <div class="mdl-cell mdl-cell--12-col">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                        @Html.TextBoxFor(m => m.Nome, new { @class = "mdl-textfield__input" })
                        <label class="mdl-textfield__label" for="nome">Nome</label>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--12-col">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                        @Html.TextBoxFor(m => m.QuantidadePessoas, new { @class = "mdl-textfield__input", @pattern = "-?[0-9]*(\\.[0-9]+)?", @type="number" })
                        <label class="mdl-textfield__label" for="quantidade">Quantidade de Pessoas</label>
                        <span class="mdl-textfield__error">Favor digitar somente número</span>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--12-col">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--3-col">
                        @Html.HiddenFor(m => m.DataHoraChegada)
                        <label>@Model.DataHoraChegada</label>
                    </div>
                </div>

                <div class="mdl-cell mdl-cell--12-col">
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                        <i class="material-icons">add_circle</i> Adicionar
                    </button>
                </div>
            </section>

            <dialog class="mdl-dialog" style="display:none">
                <div class="mdl-dialog__content">
                    <p>
                        @ViewBag.Mensagem
                    </p>
                </div>
                <div class="mdl-dialog__actions">
                    <button type="button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent close">
                        <i class="material-icons">done</i> OK
                    </button>
                </div>
            </dialog>
        </div>
    }
</div>